dubbo:
  application:
    name: dubbox-consumer
  protocol:
    host: localhost
    name: dubbo
    port: 20880
  registry:
    address: localhost:2181
    protocol: zookeeper
server:
  port: 8080
spring:
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
    suffix: .html
